require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymentsController do
  let(:valid_session) { {} }

  let(:customer) { FactoryGirl.create(:customer) }

  before :each do
    Customer.destroy_all
  end

  describe "GET index" do
    it "assigns all payments as @payments" do
      get :index, {customer_id: customer.to_param}, valid_session
      response.should be_success
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "redirects to the successful payment" do
        post :create, {customer_id: customer.to_param}, valid_session
        response.should redirect_to(customer_path(customer))
      end
    end
  end
end
