require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SurveysController do

  # This should return the minimal set of attributes required to create a valid
  # Survey. As you add validations to Survey, be sure to
  # adjust the attributes here as well.
  let(:customer) { FactoryGirl.create(:customer)}
  let(:reporting_field) {FactoryGirl.build(:reporting_field)}

  let(:valid_attributes) { { "name" => "MyText", "customer_id" => customer.id } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurveysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    Customer.destroy_all
    user = FactoryGirl.create(:user)
    sign_in user
  end


  describe "GET index" do
    it "assigns all surveys as @surveys" do
      Survey.destroy_all
      survey = Survey.create! valid_attributes
      get :index, {customer_id: customer.id}, valid_session
      assigns(:surveys).should eq([survey])
    end
  end

  describe "GET show" do
    it "assigns the requested survey as @survey" do
      survey = Survey.create! valid_attributes
      reporting_field.survey = survey
      reporting_field.save!
      get :show, {customer_id: customer.id, :id => survey.to_param}, valid_session
      assigns(:survey).should eq(survey)
      reporting_field.destroy
    end
  end

  describe "GET new" do
    it "assigns a new survey as @survey" do
      get :new, {customer_id: customer.id}, valid_session
      assigns(:survey).should be_a_new(Survey)
    end
  end

  describe "GET edit" do
    it "assigns the requested survey as @survey" do
      survey = Survey.create! valid_attributes
      get :edit, {customer_id: customer.id, :id => survey.to_param}, valid_session
      assigns(:survey).should eq(survey)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Survey" do
        expect {
          post :create, {customer_id: customer.id, :survey => valid_attributes}, valid_session
        }.to change(Survey, :count).by(1)
      end

      it "assigns a newly created survey as @survey" do
        post :create, {:survey => valid_attributes, customer_id: customer.id}, valid_session
        assigns(:survey).should be_a(Survey)
        assigns(:survey).should be_persisted
      end

      it "redirects to the created survey" do
        post :create, {:survey => valid_attributes, customer_id: customer.id}, valid_session
        response.should redirect_to(customer_survey_path(customer, Survey.last))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved survey as @survey" do
        # Trigger the behavior that occurs when invalid params are submitted
        Survey.any_instance.stub(:save).and_return(false)
        post :create, {:survey => { "name" => "invalid value" }, customer_id: customer.id}, valid_session
        assigns(:survey).should be_a_new(Survey)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Survey.any_instance.stub(:save).and_return(false)
        post :create, {:survey => { "name" => "invalid value" }, customer_id: customer.id}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested survey" do
        survey = Survey.create! valid_attributes
        # Assuming there are no other surveys in the database, this
        # specifies that the Survey created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Survey.any_instance.should_receive(:update).with({ "name" => "MyText" })
        put :update, {:id => survey.to_param, :survey => { "name" => "MyText" }, customer_id: customer.id}, valid_session
      end

      it "assigns the requested survey as @survey" do
        survey = Survey.create! valid_attributes
        put :update, {:id => survey.to_param, :survey => valid_attributes, customer_id: customer.id}, valid_session
        assigns(:survey).should eq(survey)
      end

      it "redirects to the survey" do
        survey = Survey.create! valid_attributes
        put :update, {:id => survey.to_param, :survey => valid_attributes, customer_id: customer.id}, valid_session
        response.should redirect_to(customer_survey_path(customer, survey))
      end
    end

    describe "with invalid params" do
      it "assigns the survey as @survey" do
        survey = Survey.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Survey.any_instance.stub(:save).and_return(false)
        put :update, {:id => survey.to_param, :survey => { "name" => "invalid value" }, customer_id: customer.id}, valid_session
        assigns(:survey).should eq(survey)
      end

      it "re-renders the 'edit' template" do
        survey = Survey.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Survey.any_instance.stub(:save).and_return(false)
        put :update, {:id => survey.to_param, :survey => { "name" => "invalid value" }, customer_id: customer.id}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "CARD" do
    it "redirects to the survey" do
      survey = Survey.create! valid_attributes
      put :card, {id: survey.to_param, customer_id: customer.id, what: "Web Survey"}, valid_session
      response.should redirect_to complete_surveys_path(survey_id: survey.id)
    end
    it "shows pdf card" do
      survey = Survey.create! valid_attributes
      put :card, {id: survey.to_param, customer_id: customer.id, what: "Printable Card"}, valid_session
      response.should render_template("card")
    end
    it "shows card for admin" do
      c = FactoryGirl.create (:non_active_customer)
      survey = Survey.create! valid_attributes
      survey.customer = c
      survey.save!
      put :card, {id: survey.to_param, customer_id: c.id, what: "Printable Card"}, valid_session
      response.should render_template("card")
    end
    it "shows blank card when logged in but doesn't know what to do" do
      survey = Survey.create! valid_attributes
      put :card, {id: survey.to_param, customer_id: customer.id, what: "Nobody"}, valid_session
      response.should render_template("blank_card")
    end
    it "shows blank card when logged in non-admin and customer is not active" do
      reg_user = FactoryGirl.build(:reg_user)
      c = FactoryGirl.create (:non_active_customer)
      reg_user.customer = c
      reg_user.save!
      sign_in reg_user
      survey = Survey.create! valid_attributes
      survey.customer = c
      survey.save!
      put :card, {id: survey.to_param, customer_id: c.id}, valid_session
      response.should render_template("blank_card")
      reg_user.destroy
      c.destroy
      survey.destroy
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested survey" do
      survey = Survey.create! valid_attributes
      expect {
        delete :destroy, {:id => survey.to_param, customer_id: customer.id}, valid_session
      }.to change(Survey, :count).by(-1)
    end

    it "redirects to the surveys list" do
      survey = Survey.create! valid_attributes
      delete :destroy, {:id => survey.to_param, customer_id: customer.id}, valid_session
      response.should redirect_to(customer_surveys_path(customer))
    end
  end

end
